### PR TITLE
Python Example

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
CC @romangrothausmann

**Comment by thewtex** [comment]
Requires: https://github.com/InsightSoftwareConsortium/itkwidgets/pull/226

**Comment by thewtex** [comment]
image

image

**Comment by thewtex** [comment]
@romangrothausmann thanks for the reviews.  Yes, we may need to improve for better image spacing and speed map support.

**Comment by romangrothausmann** [comment]
Sure, no problem. 

>Yes, we may need to improve for better image spacing and speed map support.

Just to prevent double work: That is already also included in @richardbeare branch:
https://github.com/richardbeare/ITKMinimalPathExtraction/tree/ConsolidateInterpolator

**Pull request merged**
