### PR TITLE
ENH: Bump ITK and replace http with https using script

### PR DESCRIPTION
**Pull request by tbirdso**
Automated reformatting with https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/Maintenance/ApplyScriptToRemotes.sh

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
This seems to have non-trivial test failures.

**Comment by tbirdso** [comment]
Seeing repeated failures of the following type:

> itk::ExceptionObject (0x5648b69046d0)
Location: "unknown" 
File: /home/runner/work/ITKMinimalPathExtraction/ITK/Modules/Filtering/FastMarching/include/itkFastMarchingUpwindGradientImageFilter.h
Line: 267
Description: ITK ERROR: FastMarchingUpwindGradientImageFilter(0x5648b6a62da0): No target point set. Cannot set the target reached mode.

**Comment by tbirdso** [comment]
Note that the failures also exist in #88.

**Comment by aylward** [comment]
Tests fixed in https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/pull/90

**Review by aylward — APPROVED** [review]
LGTM

**Pull request merged**
