### PR TITLE
DOC: Improve Python package information.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Improve Python package information:
- Make the reference in the long description match the package name and
  not the ITK project name.
- Replace the generic ITK long description for a description of the
  package.
- Make the URL be the URL of the project in GitHub.

Partially addresses:
https://github.com/InsightSoftwareConsortium/ITK/issues/326

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Thanks for pointing out @thewtex ! Let's see if c88edbb fixes them.

**Comment by thewtex** [comment]
```
  File "setup.py", line 28
    'Insight Journal, January-June 2008, http://hdl.handle.net/1926/1332.',
SyntaxError: non-keyword arg after keyword arg
```

**Comment by jhlegarreta** [comment]
Took me a while to realize... Sorry @thewtex !

**Comment by jhlegarreta** [comment]
The Travis error is unrelated. May be it has to do with this error (?):
InsightSoftwareConsortium/ITKLabelErodeDilate#22

Anyway, it'll need to be addressed in another topic.

**Pull request merged**
